<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>none</AnalysisLevel>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Accounting\Controllers\**" />
    <Compile Remove="Areas\Inventory\Data\**" />
    <Compile Remove="Areas\Suppliers\Controllers\**" />
    <Compile Remove="Areas\Suppliers\Data\**" />
    <Compile Remove="Areas\Suppliers\Models\**" />
    <Compile Remove="Core\Types\Accounting\**" />
    <Compile Remove="Extensions\Data\**" />
    <Compile Remove="Extensions\Identity\**" />
    <Compile Remove="Test-Data\**" />
    <Content Remove="Areas\Accounting\Controllers\**" />
    <Content Remove="Areas\Inventory\Data\**" />
    <Content Remove="Areas\Suppliers\Controllers\**" />
    <Content Remove="Areas\Suppliers\Data\**" />
    <Content Remove="Areas\Suppliers\Models\**" />
    <Content Remove="Core\Types\Accounting\**" />
    <Content Remove="Extensions\Data\**" />
    <Content Remove="Extensions\Identity\**" />
    <Content Remove="Test-Data\**" />
    <EmbeddedResource Remove="Areas\Accounting\Controllers\**" />
    <EmbeddedResource Remove="Areas\Inventory\Data\**" />
    <EmbeddedResource Remove="Areas\Suppliers\Controllers\**" />
    <EmbeddedResource Remove="Areas\Suppliers\Data\**" />
    <EmbeddedResource Remove="Areas\Suppliers\Models\**" />
    <EmbeddedResource Remove="Core\Types\Accounting\**" />
    <EmbeddedResource Remove="Extensions\Data\**" />
    <EmbeddedResource Remove="Extensions\Identity\**" />
    <EmbeddedResource Remove="Test-Data\**" />
    <None Remove="Areas\Accounting\Controllers\**" />
    <None Remove="Areas\Inventory\Data\**" />
    <None Remove="Areas\Suppliers\Controllers\**" />
    <None Remove="Areas\Suppliers\Data\**" />
    <None Remove="Areas\Suppliers\Models\**" />
    <None Remove="Core\Types\Accounting\**" />
    <None Remove="Extensions\Data\**" />
    <None Remove="Extensions\Identity\**" />
    <None Remove="Test-Data\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="3.9.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Areas\Identity\Models\Account\DataTransferObjects\" />
    <Folder Include="Areas\Systems\Providers\Stores\" />
    <Folder Include="Core\Types\PurchasesAndSales\" />
    <Folder Include="Models\Entity\PayrollSpace\" />
  </ItemGroup>
</Project>
